// shots/perf/after.md from scripts/perf-capture.mjs's JSON (README "Performance"): a before -> after
// summary (tier x view x scenario: mean, p95, max, frames > 50 ms, draw calls, GPU ms per pass),
// the load table before -> after, then each after capture's own tables.
//
//   node scripts/perf-report.mjs shots/perf/before.json paced.json uncapped.json fps30.json > shots/perf/after.md
import { readFileSync } from "node:fs";

const [beforeF, pacedF, uncappedF, fps30F, vsyncF] = process.argv.slice(2);
const load = (f) => (f ? JSON.parse(readFileSync(f, "utf8")) : []);
const before = load(beforeF);
const paced = load(pacedF);
const uncapped = load(uncappedF);
const fps30 = load(fps30F);
const vsync = load(vsyncF);
const key = (r) => `${r.tier}|${r.view}|${r.scenario}`;
const find = (rows, r) => rows.find((x) => key(x) === key(r));
const PASSES = ["shadow", "colour", "aoNormal", "ao", "bloom", "output", "fxaa", "seeThrough"];
const passes = (r) => (r ? PASSES.map((p) => (r.passes[p] === undefined ? "-" : r.passes[p])).join(" / ") : "-");
const px = (r) => (r?.mem?.drawingBuffer ? `${r.mem.drawingBuffer[0]}x${r.mem.drawingBuffer[1]}` : "?");
const L = [];
L.push("# Performance after", "");
L.push(`Generated by scripts/perf-report.mjs from ${[beforeF, pacedF, uncappedF, fps30F].filter(Boolean).join(", ")}. Same machine, harness and spots as shots/perf/before.md (Vega 11, ANGLE Vulkan, headless Chrome, vsync off, a fresh browser per row, 10 s per row, stats after the first second). Before had no frame cap: its rows are uncapped. After ships a 60 fps cap: "after (60 cap)" is what a player gets; "after (uncapped)" (\`fps=0\`) is the work per frame, the like-for-like comparison with before. Phone rows: 1080x2400 at DPR 2.6, emulated pixels drawn by the Vega 11 (no phone GPU).`, "");
L.push("## Reading it", "");
L.push("- The shipping build caps at 60 fps: every Full and Lite row has 0 frames over 50 ms (max 28-31 ms, before: 387-1346 ms); with vsync on (below) Full's 1080p mean is 17.3-17.9 ms (GPU 13.8-14.3 ms a frame: over the 12 ms target), every other row 16.7 ms flat.", "- The before rows' long frames were the see-through's synchronous read-back (`sync read-back`, up to 1346 ms) and, uncapped, a GPU queue run seconds deep that stalled a random GL call (`cpu: colour / shadow / bloom`). The uncapped after rows still show the second kind (GPU-bound with vsync and the cap off: a harness artifact; a 60 Hz browser never queues that deep) and no sync read at all; their GPU / CPU ms per frame are the work.", "- Timer query ms on this APU move with its clock (DVFS) and run to run by 10-20 %: compare columns within one capture.", "");
L.push("## Summary: before -> after", "");
L.push("Frame time = rAF interval between drawn frames (ms). GPU per pass (ms, EXT_disjoint_timer_query_webgl2, exclusive): shadow / colour / aoNormal / ao (+ composite) / bloom / output / fxaa / seeThrough.", "");
L.push("| tier | view | scenario | canvas px before -> after | mean before -> uncapped / 60 cap | p95 before -> uncapped / 60 cap | max before -> uncapped / 60 cap | > 50 ms before -> uncapped / 60 cap | GPU ms/frame before -> uncapped | CPU ms/frame before -> uncapped | draw calls before -> after | GPU per pass before | GPU per pass after (uncapped) |");
L.push("|---|---|---|---|---|---|---|---|---|---|---|---|---|");
for (const b of before) {
  const u = find(uncapped, b);
  const p = find(paced, b);
  const v = (r, k) => (r ? r[k] : "-");
  L.push(`| ${b.tier} | ${b.view} | ${b.scenario} | ${px(b)} -> ${px(u ?? p)} | ${b.mean} -> ${v(u, "mean")} / ${v(p, "mean")} | ${b.p95} -> ${v(u, "p95")} / ${v(p, "p95")} | ${b.max} -> ${v(u, "max")} / ${v(p, "max")} | ${b.over50} -> ${v(u, "over50")} / ${v(p, "over50")} | ${b.gpuMean} -> ${v(u, "gpuMean")} | ${b.cpuMean} -> ${v(u, "cpuMean")} | ${b.calls} -> ${v(u ?? p, "calls")} | ${passes(b)} | ${passes(u)} |`);
}
if (vsync.length) {
  L.push("", "## The 60 fps cap with vsync on (the browser's own 60 Hz frame clock: what a player's screen does)", "");
  L.push("The capture above runs with vsync off, where rAF fires at irregular times and the pacer's slots jitter (its p95 ~27 ms is that, not hitches). With the browser's frame clock on, the same build:", "");
  L.push("| tier | view | scenario | mean | p95 | max | > 50 ms | GPU ms/frame | CPU ms/frame |");
  L.push("|---|---|---|---|---|---|---|---|---|");
  for (const r of vsync) L.push(`| ${r.tier} | ${r.view} | ${r.scenario} | ${r.mean} | ${r.p95} | ${r.max} | ${r.over50} | ${r.gpuMean} | ${r.cpuMean} |`);
}
if (fps30.length) {
  L.push("", "## 30 fps pacing (`fps=30`, Settings → Frame rate 30) against the 60 cap", "");
  L.push("Frames drawn per second halve, and so does the GPU's busy time per second at Lite (frames x GPU ms). The GPU ms of one frame moves with the Vega 11's clock (DVFS: at Lite's load it sits at 200-450 MHz at 60 fps and at its 200 MHz floor at 30, sampled from pp_dpm_sclk), so per-frame ms are not comparable across rates; frames drawn and busy ms per second are. Full at 30 is not a target (its fly-over lost frames while the clock ramped).", "");
  L.push("| tier | view | scenario | fps 60 cap -> 30 | frames drawn (10 s) | GPU ms/frame | GPU busy ms per second | > 50 ms |");
  L.push("|---|---|---|---|---|---|---|---|");
  for (const t of fps30) {
    const p = find(paced, t);
    const busy = (r) => (r ? Math.round(r.fps * r.gpuMean) : "-");
    L.push(`| ${t.tier} | ${t.view} | ${t.scenario} | ${p?.fps ?? "-"} -> ${t.fps} | ${p?.drawn ?? "-"} -> ${t.drawn} | ${p?.gpuMean ?? "-"} -> ${t.gpuMean} | ${busy(p)} -> ${busy(t)} | ${p?.over50 ?? "-"} -> ${t.over50} |`);
  }
}
L.push("", "## Load: before -> after (the spot rows' pages; repeat = a second visit in the same browser context)", "");
L.push("| tier | view | first frame ms | env build ms (measure / build) | bytes before first frame | repeat: first frame ms | repeat: env build ms (measure / build) | render targets + shadow est. MB |");
L.push("|---|---|---|---|---|---|---|---|");
const MB = (b) => (b / 1048576).toFixed(1);
for (const b of before.filter((r) => r.scenario === "spot")) {
  const a = find(paced, b);
  if (!a) continue;
  L.push(`| ${b.tier} | ${b.view} | ${b.load.firstFrameMs} -> ${a.load.firstFrameMs} | ${b.load.envMs} / ${b.load.look?.envBuildMs ?? "-"} -> ${a.load.envMs} / ${a.load.look?.envBuildMs ?? "-"} | ${MB(b.load.bytesBeforeFirst)} -> ${MB(a.load.bytesBeforeFirst)} MB | ${b.repeat?.firstFrameMs} -> ${a.repeat?.firstFrameMs} | ${b.repeat?.envMs} / ${b.repeat?.look?.envBuildMs ?? "-"} -> ${a.repeat?.envMs} / ${a.repeat?.look?.envBuildMs ?? "-"} | ${MB(b.mem.targetBytes)} -> ${MB(a.mem.targetBytes)} |`);
}
for (const [name, f] of [["60 fps cap (shipping)", pacedF], ["uncapped (fps=0)", uncappedF], ["30 fps pacing", fps30F], ["60 fps cap, vsync on", vsyncF]]) {
  if (!f) continue;
  const md = readFileSync(f.replace(/\.json$/, ".md"), "utf8").split("\n").slice(1);
  L.push("", `## Capture: ${name}`, "", ...md.map((l) => (l.startsWith("## ") ? `#${l}` : l)));
}
process.stdout.write(L.join("\n") + "\n");
