// Refreshes the vendored assets/ from the make-it-in-china asset library: the town's sources
// (town_layout/town.json and the walk grid it names), then src/town.json ported from them
// (scripts/port-town.mjs), then only the GLBs src/layout.json and src/town.json use, plus an
// index.json listing only those. Run after the library is rebuilt (tools/blender/build_all.py,
// tools/blender/town_layout.py) or a layout starts using a new asset:
//
//   npm run assets:sync -w @silver-tongue/world3d      (WORLD3D_ASSETS=... to point elsewhere)
//
// The library defaults to ../assets next to the repo checkout (the make-it-in-china layout).
import { copyFileSync, existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { portTown, readTownSources, townJsonText } from "./port-town.mjs";
import { copyUsed } from "./used-assets.mjs";

const here = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = process.env.WORLD3D_ASSETS ?? join(here, "..", "..", "..", "assets");
const out = join(here, "assets");
if (!existsSync(join(src, "index.json"))) throw new Error(`no asset library at ${src} (set WORLD3D_ASSETS)`);

// The town first: its port decides which GLBs the outdoors uses.
const { town, grid, index } = readTownSources(src);
const ported = portTown(town, grid, index);
writeFileSync(join(here, "src", "town.json"), townJsonText(ported));

const n = copyUsed(src, out, [join(here, "src", "layout.json"), join(here, "src", "town.json")]);
// The town's sources, so `npm run port-town` and the staleness test run from the repo alone.
const townFiles = [join("town_layout", "town.json"), town.walkable.grid.replace(/\.json$/, "") + ".json"];
for (const f of townFiles) {
  mkdirSync(join(out, dirname(f)), { recursive: true });
  copyFileSync(join(src, f), join(out, f));
}
writeFileSync(
  join(out, "README.md"),
  `# Vendored assets\n\nGenerated by make-it-in-china tools/blender/build_all.py (GLBs) and tools/blender/town_layout.py\n(\`town_layout/town.json\`, \`landscape/terrain_town_walkable.json\`); do not hand-edit. Only the GLBs\n\`src/layout.json\` and \`src/town.json\` use, plus an \`index.json\` listing only those, and the town's\nsources that \`scripts/port-town.mjs\` turns into \`src/town.json\`.\n\nRegenerate with \`npm run assets:sync -w @silver-tongue/world3d\` (copies from \`WORLD3D_ASSETS\`,\ndefault \`../assets\` next to the repo checkout, and re-ports the town).\n`,
);
const size = (d) => readdirSync(d).reduce((s, f) => s + (statSync(join(d, f)).isDirectory() ? size(join(d, f)) : statSync(join(d, f)).size), 0);
console.log(`synced packages/world3d/assets: ${n} GLBs and the town's sources from ${src}, ${(size(out) / 1048576).toFixed(1)} MB; ported src/town.json`);
